Repository IsyFact/isy-web, pull requests merged in 2024-02, with the labels that each got.

#40 [Sprint 87] ISY-344: IF3 - Umstellung auf isy-security
  CHANGELOG.md
  isy-web-doc/src/docs/antora/modules/isy-web/images/konzept/integration-baustein-sicherheit-klassendiagramm.png
  isy-web-doc/src/docs/antora/modules/isy-web/images/konzept/integration-baustein-sicherheit-sequenzdiagramm.png
  isy-web-doc/src/docs/antora/modules/isy-web/pages/konzept/anhaenge.adoc
  isy-web-doc/src/docs/antora/modules/isy-web/pages/konzept/konzept.adoc
  isy-web-doc/src/docs/antora/modules/isy-web/pages/nutzungsvorgaben/nutzungsvorgaben.adoc
  isy-web-lib/pom.xml
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/autoconfigure/ControllerAutoConfiguration.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/comparator/NullSafeBeanComparator.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/exception/OptimisticLockHandler.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/filetransfer/DateitypEnum.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/global/GlobalFlowController.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/global/HeaderHelper.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/global/IsyWebKonfigurationHelper.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/global/MessageController.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/jsf/components/charpickerdinnorm91379/CharPickerDinNorm91379Controller.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/jsf/components/datatable/DataTableInMemoryController.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/jsf/components/datatable/SortDirection.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/jsf/components/listpicker/ListpickerGuiItem.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/jsf/components/listpicker/ListpickerGuiKonfiguration.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/jsf/components/navigationmenu/NavigationMenuModel.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/jsf/components/navigationmenu/controller/NavigationMenuController.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/jsf/components/navigationmenu/generieren/impl/NavigationMenuGenerierenAusKonfiguration.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/jsf/components/specialcharpicker/SpecialCharPickerWidget.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/jsf/components/upload/UploadHelper.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/jsf/renderer/NoLabelHtmlCheckboxRenderer.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/jsf/renderer/NoLabelHtmlRadioRenderer.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/layout/HilfeController.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/layout/HilfeModel.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/layout/LinksnavigationController.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/layout/QuicklinksController.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/layout/QuicklinksGruppeModel.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/locale/LocaleConfiguration.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/security/WebDelegatingAccessDecisionManager.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/tempwebresource/controller/ResourceController.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/webflow/titles/BreadcrumbListener.java
  isy-web-lib/src/main/java/de/bund/bva/isyfact/common/web/webflow/titles/TitlesHelper.java
  isy-web-lib/src/test/java/de/bund/bva/isyfact/common/web/autoconfigure/AutoConfigurationTest.java
  isy-web-lib/src/test/java/de/bund/bva/isyfact/common/web/global/GlobalFlowControllerTest.java
  isy-web-lib/src/test/java/de/bund/bva/isyfact/common/web/layout/LinksnavigationControllerTest.java
  isy-web-lib/src/test/resources/resources/sicherheit/rollenrechte.xml
Labels: high

#46 build: ISY-640 configure flatten plugin to minimize pom content
  pom.xml
Labels: medium, build

#61 ISY-615 Snapshot Deployment to GitHub Packages
  .github/workflows/maven_build.yml
Labels: ci

#63 ci: fix build and release workflows
  .github/workflows/maven_build.yml
  .github/workflows/maven_release.yml
Labels: ci
